### ISSUE TITLE
E2E smoke test catches all kinds of dependency errors

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-js#1002]
Our smoke test should have caught #998 , but didn't

**Comment by lachrist** [comment]
@dividedmind FYI https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md

**Comment by dividedmind** [comment]
> @dividedmind FYI https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md

We're actually using this rule. Not sure why it didn't catch this.

**Comment by lachrist** [comment]
Not enough sacrifice to Cthulhu?

**Comment by dividedmind** [comment]
> Not enough sacrifice to Cthulhu?

Maybe. Or maybe it's because of #1005 — although I did quickly try fixing it and it still didn't catch it.
