### ISSUE TITLE
Sequence diagram bug fixes

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-js#1008]
- [x] Clicking on the HTTP client request in [the sequence diagram](http://localhost:6006/?path=/story/pages-vs-code--extension-with-default-sequence-view) , then clicking it again in the sidebar causes the entire sidebar display to become blank
- [x] Clicking the External Service 127.0.0.1:9515 and then clicking Hide  causes an error “Invalid attempt to destructure non-iterable instance.”

**Comment by brikelly** [comment]
Are these going to be all in the same PR? If not, we should split this up so it doesn't languish as a big batch umbrella story.

**Comment by ahtrotta** [comment]
I'll clean this up now
