### ISSUE TITLE
OpenAPI: `GET`, `DELETE` operations cannot have a `requestBody`

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-js#1010]
OpenAPI does not support `requestBody` within `GET`, `DELETE` methods because [it does not have explicitly defined semantics](https://www.rfc-editor.org/rfc/rfc7231#section-4.3.5).

See the following GitHub issue: https://github.com/OAI/OpenAPI-Specification/issues/1801

The following generated definition is invalid:
```yaml
  /api_keys/{id}:
    delete:
      responses:
        '302':
          content: {}
          description: Found
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                commit:
                  type: string
                utf8:
                  type: string
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
```

**Comment by kgilpin** [comment]
Seems like this could be a scanner rule then - since sending a payload to a
DELETE request is invalid.
