### ISSUE TITLE
Hovering over a return shows the value being returned

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-js#1050]
Proposal is to allow return values to be revealed in the Sequence Diagram view. They are shown in the left panel when the event is selected, but it could be useful to do so in-place, similar to how values are shown in Trace View. Could also show parameters being passed to function calls but that might be too cluttered.

![Image](https://user-images.githubusercontent.com/573108/220173746-3b30648e-08d5-406e-8afa-3fd94c9029a5.png)

**Comment by kgilpin** [comment]
I feel like we could ship without doing all of this.

How is the determination made about what’s essential for v1 completeness?

**Comment by brikelly** [comment]
Yes this issue is marked as `enhancement` because it's definitely not required for shipping. 

For the first release, we do want to fix the bugs labeled as `bug`, though.

**Comment by ahtrotta** [comment]
This is redundant because of #1324

**Comment by ahtrotta** [comment]
Sorry, I misunderstood, this is not redundant.
