### ISSUE TITLE
Return arrow pointing in the wrong direction

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-js#1053]
![Image](https://user-images.githubusercontent.com/573108/220192689-b49bd888-14ea-420f-880b-03ed65b734d1.png)

Found in Solidus map (look at the bottom of the sequence, graphic above was taken with many lifelines hidden for clarity):

[1676598908_493438_http_localhost_3000_cart_link.appmap.json.zip](https://github.com/getappmap/appmap-js/files/10787589/1676598908_493438_http_localhost_3000_cart_link.appmap.json.zip)

**Comment by ahtrotta** [comment]
As far as I can tell, this is how the sequence diagram is supposed to work. If a call doesn't have a return value, then there isn't a dashed return value arrow. In the above image, the call to `[]` doesn't have a return value, and the dashed left arrow marked with `boolean` is the return value from the call to `cart_link` a bit above:



![Image](https://user-images.githubusercontent.com/45714532/220761492-d5a99feb-317a-4325-8fcc-f145b501fa9b.png)

**Comment by kgilpin** [comment]
That’s correct. It’s not a bug.

You can tell which call it’s returning from because it ends that box that
runs down the lifeline.

**Comment by kgilpin** [comment]
The way I wrote it, if a function call returns null-ish then the return is
omitted. Makes the diagram more compact.

**Comment by brikelly** [comment]
Great! Happy to close this then. Thanks!
