### ISSUE TITLE
Lifeline not found when searching for it

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-js#1056]
![Image](https://user-images.githubusercontent.com/573108/220195937-86b7ca18-6ab4-44a7-a639-c3ef9de04096.png)

Clicking on one of the Lifeline boxes in this map named `solidus_starter_frontend` made it show up correctly in the left panel, but the same string when typed into the `search code objects...` box revealed no results

Loom: https://www.loom.com/share/bfe7e3f85bd8497d988286678563efd9

Found in map from Solidus:
[1676598908_493438_http_localhost_3000_cart_link.appmap.json.zip](https://github.com/getappmap/appmap-js/files/10787639/1676598908_493438_http_localhost_3000_cart_link.appmap.json.zip)

**Comment by Znaidiukandrii** [comment]
Hi @brikelly 
I am checking.
