### ISSUE TITLE
The first request in a sequence diagram begins the "box" too high on the lifeline

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-js#1061]
### Issue

In the sequence diagram, the first lifeline is activated (e.g. instead of a thin dashed line it is a thick solid line), but it is activated too high on the lifeline. This should be a vertical dotted line until the arrow pointing to the call to `GET /cart_link` begins:

![Image](https://github.com/getappmap/appmap-js/assets/45714532/34428224-395d-477d-a1ba-13b7467857ab)

### Details

* Please make it so that the first lifeline is "activated" at the appropriate position adjacent to the first call arrow.
* The SCSS for the active lifeline is [here](https://github.com/getappmap/appmap-js/blob/main/packages/components/src/scss/_variables.scss#L92).

**Comment by ahtrotta** [comment]
This lifeline is also making our exported SVG render wonky:



![Image](https://user-images.githubusercontent.com/45714532/221039906-1a57da39-9f48-4dfe-9883-ece256bc4a6a.png)

**Comment by ahtrotta** [comment]
@brikelly, should we prioritize this because it's messing with the SVG export?

**Comment by brikelly** [comment]
Yes I think so. SVG exports will be a very visible artifact along teams adopting this. That said, it might not need to hold up the release if we can fast-follow with a fix.
