### ISSUE TITLE
Sequence Diagram has a legend

### ISSUE THREAD

**Issue by Daniel-Warner-X** [getappmap/appmap-js#1066]
When a user clicks on the 'i' icon in the lower right hand corner of the Dependency Map or Trace View, they get a legend explaining what the different visual indicators on the map mean.

![Image](https://user-images.githubusercontent.com/1229326/220978613-99a06635-eaf7-42a0-8194-0d8810b8851e.png)

![Image](https://user-images.githubusercontent.com/1229326/220978747-e8b94e67-3c90-4aa4-af51-2a14ba8fbb4a.png)

The Sequence Diagram is not included in this information. Clicking the 'i' icon in the Sequence Diagram view produces the same double legend that is used for the Dependency Map and Trace View.

Quick fix would be to add legend content for the Sequence Diagram. Better solution would be to have the 'i' icon produce a context-specific legend for the visualization that the user is looking at.

**Comment by kgilpin** [comment]
This seems a bit less important than with the other diagrams since sequence
diagram is a standard that we are following.

I wonder if linking out to web docs would be better anyway. The legend
tends to obscure the diagram that the user is trying to look at.
