### ISSUE TITLE
Prototype of flame graph graphic generation

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-js#1182]
Goal is to go end-to-end quickly with an OSS library (perhaps [this one](https://github.com/brendangregg/FlameGraph), if the license permits it) and use it with AppMap data to create flame graphs representing time spent in each function.

This can begin with just a CLI tool that takes a map and outputs a graphic file. Once that plumbing is built, we can create stories to get this fully productized within VS Code and JetBrains.

**Comment by kgilpin** [comment]
@lachrist https://github.com/spiermar/d3-flame-graph - I used this one long ago and it was fine.
