### ISSUE TITLE
AppMaps are slow to load and interact with

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-js#1183]
## Description 

Selecting a sequence diagram call event takes 2 seconds:

[230515211755.appmap.json.zip](https://github.com/getappmap/appmap-js/files/11488980/230515211755.appmap.json.zip)

Applying elapsed time filter takes 12 seconds:

[Dashboard_when_looking_at_actions_panel_shows_the_correct_counts_on_current_dashboard_tab.appmap.json.zip](https://github.com/getappmap/appmap-js/files/11531685/Dashboard_when_looking_at_actions_panel_shows_the_correct_counts_on_current_dashboard_tab.appmap.json.zip)

This Java AppMap takes almost 20 seconds to load but is less than 10MB in size, and it doesn't show the pink "spinner" when loading in the IDE: [org_finos_waltz_integration_test_inmem_service_FlowPermissionCheckerTest_findPermissionsForSpecDecorator.appmap.json.zip](https://github.com/getappmap/appmap-js/files/12701376/org_finos_waltz_integration_test_inmem_service_FlowPermissionCheckerTest_findPermissionsForSpecDecorator.appmap.json.zip)

## Prior work

Build on top of https://github.com/getappmap/appmap-js/issues/1390

**Comment by kgilpin** [comment]
Thanks for looking into this @dustinbyrne . My feeling is that we want to start with some of the techniques that you suggest at the end of your comment, and the work our way up if it's not working.

For example, if we are using a known anti-pattern, let's fix that. We know that there are a lot of elements outside the visible viewport - can we optimize those away? Is the flame graph slowing down the UI even when it's not visible? Can we reduce the number of elements showing in the flame graph (e.g. hide anything smaller than 1 pixel). 

Then if we still haven't got the performance we need, we look at using non-standard Vue techniques.

**Comment by ahtrotta** [comment]
Closed as of #1434
