### ISSUE TITLE
Add commands to 'Record AppMaps' view

### ISSUE THREAD

**Issue by Daniel-Warner-X** [getappmap/appmap-js#1199]
Test a new design of the 'Record AppMaps' view that includes commands for the user to copy/paste. For example 'DISABLE_SPRING=true rails test' or 'DISABLE_SPRING=true rails server.' The goal would be to clarify to the user the next step they need to take.

![Image](https://user-images.githubusercontent.com/1229326/242345554-5056ca86-3902-42ea-9e15-6407b225b7dd.png)

**Comment by kgilpin** [comment]
This is done in the new setup flow.
