### ISSUE TITLE
Stats command should work with relative path

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-js#1200]
### Issue

Currently, the stats command only works with absolute file paths, like this:
```
npx @appland/appmap@latest stats --appmap-file /Users/kgilpin/source/land-of-apps/sample_app_6th_ed/tmp/appmap/minitest/Users_index_index_as_admin_including_pagination_and_delete_links.appmap.json
```

### Details

* The `stats` command code can be found [here](https://github.com/getappmap/appmap-js/blob/main/packages/cli/src/cmds/stats/stats.ts).
* The tests should be added to [this test file](https://github.com/getappmap/appmap-js/blob/main/packages/cli/tests/unit/stats/stats.spec.ts).
* The `stats` command should work with relative file paths.
* The `stats` command should work with file names (the command should just check the current directory).
* Please add a test to make sure that it works with a file name where the file is in the current working directory.
* Please add a test to make sure that it does not analyze a file when a file name is passed but the file is in a child directory.
* Please add a test to make sure it works with relative file paths.

**Comment by kgilpin** [comment]
@ahtrotta can you finish speccing this and apply `well-specified`? Should be easy.
