### ISSUE TITLE
Use --ignore-cached when running npx, so that the user will always be upgraded

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-js#1207]
@dividedmind could you tackle this one? It's pretty small and self-evident from the description, hopefully.

**Comment by dividedmind** [comment]
Which npx does it refer to? Running appmap-agent-js? Are we surfe it's not enough to just use `@latest`? I'm worried ignoring the cache will lead to redownloading every time. Also, it does not appear `--ignore-cached` option exists.

**Comment by brikelly** [comment]
This was actually in the context of the CLI installer, not the JS agent necessarily. @dustinbyrne any thoughts on the `prefer-online` check over `ignore-cached`?

**Comment by dividedmind** [comment]
The CLI doesn't run itself. Is this issue in the correct repository?

**Comment by brikelly** [comment]
> The CLI doesn't run itself. 

Not sure what you mean by this? Anyway, this is for the CLI, yes. 

> any thoughts on the prefer-online check over ignore-cached?

We discussed this today and it looks like `prefer-online` will be better, assuming it really does work the way it's described.

**Comment by dividedmind** [comment]
> Not sure what you mean by this? Anyway, this is for the CLI, yes.

This issue is in appmap-js, but it seems you want to change vscode-appmap and intellij-appmap instead.
