### ISSUE TITLE
The Code Objects view also lists External Service Calls

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-js#1267]
For users in heavy microservices environments, aggregating external HTTP calls will be very useful. 

![Image](https://user-images.githubusercontent.com/573108/252787134-b0921ef8-8bc6-4d50-812e-5f127948cd8a.png)

Solving this issue will involve adding a 4th item to the list above. Service calls are already indexed so the work here should be minimal.

**Comment by kgilpin** [comment]
And Exceptions :-)
