### ISSUE TITLE
Branch feat/preflight-rebase is tested, reviewed and merged

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-js#1273]
https://github.com/getappmap/appmap-js/pull/1164 is a draft PR that is currently being used for Analysis in CI. From this branch I have been building linux binaries by hand and publishing releases like this one - https://github.com/getappmap/appmap-js/releases/tag/%40appland%2Fappmap-preflight-v1.0-pre.29

The GitHub Action @getappmap/install-action downloads and installs these binaries. So, now that Analysis in CI is moving forward, we need to give this branch a proper test, review, release treatment.

**Comment by ahtrotta** [comment]
I've copied #1164 and re-worked some of the git history so that it's a bit cleaner and easier to review. See #1286.

**Comment by ahtrotta** [comment]
The only differences are:

1. I changed the name back to `appmap` from `appmap-preflight`
2. I removed `node-fetch` from octokit [here](https://github.com/getappmap/appmap-js/pull/1286/commits/4b4527c604c623ef4853a030680c5bb179205a4e) because it was causing problems in CI

**Comment by ahtrotta** [comment]
@kgilpin is removing `node-fetch` from octokit going to be a problem?

**Comment by kgilpin** [comment]
> @kgilpin is removing `node-fetch` from octokit going to be a problem?

@ahtrotta https://github.com/octokit/octokit.js/blob/main/README.md#fetch-missing

**Comment by kgilpin** [comment]
> The only differences are:
> 
> 1. I changed the name back to `appmap` from `appmap-preflight`

If you change the name, then the `install-action` command won't work. So we may want to wait on that a bit longer. Or, the `install-action` will need to be updated.

**Comment by ahtrotta** [comment]
Can we just run our GH Action with Node 18 or above?

**Comment by kgilpin** [comment]
I'm not sure?

You can also try downgrading octokit.

**Comment by ahtrotta** [comment]
`analyze`, `restore`, `compare`, and `compare-report` have been released to `main`
