### ISSUE TITLE
The Flame Graph details inspector renders outside of vertical height on app.land

### ISSUE THREAD

**Issue by Daniel-Warner-X** [getappmap/appmap-js#1283]
When viewing a link to an AppMap from the preflight report the Flame Graph renders at the bottom of the page. The inspector is not viewable unless you manually scroll the entire browser window. Note the scroll bars:

![Image](https://user-images.githubusercontent.com/1229326/255274481-2bf93f34-f4ec-4d54-8163-7196b1527ac8.png)

The issue is not apparent in the IDE...

![Image](https://user-images.githubusercontent.com/1229326/255275080-7c97d751-f819-471f-9f13-e5cb4779fa2e.png)

Reproduce the issue by clicking an AppMap link the preflight report on this PR: https://github.com/land-of-apps/rails_tutorial_sample_app_7th_ed/pull/16

**Comment by typaulhus** [comment]
I have 2 PRs for this fix.

1. [app.land update](https://github.com/getappmap/appmap-server/pull/1261)
2. [Extension update](https://github.com/getappmap/appmap-js/pull/1297) that will bring styling to IDEs
