### ISSUE TITLE
"New" AppMaps are missing from preflight archive

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-js#1318]
See 'New AppMaps' in https://github.com/getappmap/appmap-services/pull/3#issuecomment-1681589842

**Comment by kgilpin** [comment]
@dustinbyrne this is actually the "preflight" archive - [appmap-preflight-282a545f9892ab43b207c02d2c27fd484aad1354-65489a0666e1b0db0122f2e05bec8e4e68c404af.tar.gz](https://github.com/getappmap/appmap-services/suites/15173990067/artifacts/867037083)
