### ISSUE TITLE
OpenAPI Generation OOMs on Misago Project

### ISSUE THREAD

**Issue by petecheslock** [getappmap/appmap-js#1342]
On the Misago project configured with AppMap - when generating openapi using either the binary release or `npx` will cause an OOM.  

<details>
  <summary>Error stacktrace</summary>

```
Generating OpenAPI definitions
appmap openapi -d tmp/appmap --appmap-dir . --output-file openapi.yml

<--- Last few GCs --->

[2275:0x42c3360]    85031 ms: Scavenge (reduce) 2043.0 (2081.8) -> 2042.8 (2082.3) MB, 7.1 / 0.0 ms  (average mu = 0.339, current mu = 0.309) allocation failure; 
[2275:0x42c3360]    85086 ms: Scavenge (reduce) 2043.4 (2082.3) -> 2043.1 (2082.8) MB, 5.8 / 0.0 ms  (average mu = 0.339, current mu = 0.309) allocation failure; 
[2275:0x42c3360]    85157 ms: Scavenge (reduce) 2043.8 (2082.8) -> 2043.7 (2083.3) MB, 28.8 / 0.0 ms  (average mu = 0.339, current mu = 0.309) allocation failure; 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x9ff550 node::Abort() [appmap]
 2: 0x921800 node::FatalError(char const*, char const*) [appmap]
 3: 0x11d484e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [appmap]
 4: 0x11d4afa v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [appmap]
 5: 0x13bd175  [appmap]
 6: 0x13be0a8 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [appmap]
 7: 0x13cc393 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::internal::GarbageCollectionReason, char const*, v8::GCCallbackFlags) [appmap]
 8: 0x13ccfd0 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [appmap]
 9: 0x13a5e58 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [appmap]
10: 0x13a70e4 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [appmap]
11: 0x1385b69 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [appmap]
12: 0x17726d6 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [appmap]
13: 0x1bb6239  [appmap]
Aborted (core dumped)


/home/runner/work/_actions/getappmap/archive-action/v1/dist/webpack:/archive-appmap-action/src/executeCommand.ts:65
                reject(new Error(`Command failed with code ${code}`));
^
Error: Command failed with code 134
    at ChildProcess.<anonymous> (/home/runner/work/_actions/getappmap/archive-action/v1/dist/webpack:/archive-appmap-action/src/executeCommand.ts:65:1)
    at ChildProcess.emit (node:events:513:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
```
</details>

This happens both locally on a high memory laptop as well as inside [a github action](https://github.com/land-of-apps/Misago/actions/runs/6052139090/job/16425286426)

Steps used to recreate:

1) Clone the `appmap-analysis` branch on [Misago fork](https://github.com/land-of-apps/Misago/tree/appmap-analysis)
2) Create virtualenv `python -m venv test`
3) Activate venv `source test/bin/activate`
4) pip install `pip install -r requirements.txt`
5) `<Start Docker Desktop for Postgresql requirement>`
6) Run `./doit.sh` to start the Postgresql container and export environment variables
7) Run pytest `pytest --no-cov` to generate appmaps for the project
8) Run `appmap openapi -d tmp/appmap --appmap-dir . --output-file openapi.yml` FAILURE
9) Run `npx appmap openapi -d tmp/appmap --appmap-dir . --output-file openapi.yml` FAILURE
10) `export NODE_OPTIONS="--max_old_space_size=16384"`
11) After exporting the NODE_OPTIONS run `npx appmap openapi -d tmp/appmap --appmap-dir . --output-file openapi.yml` SUCCESS
12) After exporting the NODE_OPTIONS run `appmap openapi -d tmp/appmap --appmap-dir . --output-file openapi.yml` FAILURE

**Comment by kgilpin** [comment]
Is there an AppMap archive that can be downloaded to reproduce this? That would be simpler than running a test environment. Are any of the AppMaps especially large?

**Comment by petecheslock** [comment]
Here's a tar of the appmaps.  checking them it looks like the largest ones are 10-15MB so not terrible huge (no multi-GB ones)
[Misago-appmaps.tar.gz](https://github.com/getappmap/appmap-js/files/12525013/Misago-appmaps.tar.gz)

**Comment by kgilpin** [comment]
@petecheslock as a workaround I think we should add `include-dirs` and `exclude-dirs` inputs to the archive action, so that you can direct the action to include or exclude folders within `appmap_dir`. 

It's not clear if the `requests` data generated by appmap-python in Misago is useful or not, but since this issue has come up once, it's likely to come up again.

**Comment by kgilpin** [comment]
I've confirmed that this problem is simply due to there being so many AppMaps that the OpenAPI generator runs out of memory holding the http server request data in memory. I've prototyped a solution in which the request data is segmented out by HTTP path, and staged into files. Then each file is processed in turn to generate the OpenAPI definitions for that path.
