### ISSUE TITLE
OpenAPI generation fails on sample-app-6th-edition

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-js#1346]
This failure occurred in [this Action job](https://github.com/land-of-apps/sample_app_6th_ed/actions/runs/6041572818/job/16394817968#step:12:1) within [this repo](https://github.com/land-of-apps/sample_app_6th_ed):

```
npx @appland/appmap@latest openapi --output-file openapi.yml
Unexpected token '{'
Error: Process completed with exit code 1.
```

**Comment by petecheslock** [comment]
Project was using legacy appmap GH action - that's been updated.  https://github.com/land-of-apps/sample_app_6th_ed/blob/appmap-e2e/.github/workflows/main.yml
