### ISSUE TITLE
API changes in PR report contain extra confusing "paths." strings

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-js#1350]
Our API changes in PR reports look like this:
`paths./v1/usage`
But they should really look something like this:
`GET /v1/usage`

For example:
<img width="620" alt="Screenshot 2023-09-03 at 11 30 22 PM" src="https://github.com/getappmap/appmap-js/assets/573108/e9aea00c-7403-483e-a3a5-c8fcc5608d04">

Since we use [this library](https://www.npmjs.com/package/openapi-diff) for performing the OpenAPI diff, we might want to consider just not printing the `paths.` substring in the summary section to at least make it more readable.

**Comment by kgilpin** [comment]
The format of that string is the sequence of keys in the openapi, so it’s
very predictable. We can reformat that string to match the format we want.
