### ISSUE TITLE
New projects show incorrect state in the green/yellow "progress circle"

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-js#1383]
Fresh projects show inconsistent project step state in the green/yellow circle. New Ruby project shows Explore AppMaps and Runtime Analysis as green, for example: 

![Image](https://user-images.githubusercontent.com/573108/268424377-bf161ee6-d16e-494f-9a76-5e67eb1de48e.png)

It seems to behave a little better in Python. 

Each language also has the issue where just viewing the Runtime Analysis step makes it go green.

**Comment by dustinbyrne** [comment]
>Fresh projects show inconsistent project step state in the green/yellow circle. New Ruby project shows Explore AppMaps and Runtime Analysis as green  

Presumably this is a fresh clone of the repo, but you've used this path before? We store metadata based on the project path. For a full and complete "clean slate", you'd need to run the "reset usage" command.

>Each language also has the issue where just viewing the Runtime Analysis step makes it go green.  

This is the intended design. Unless you're saying it's odd that it can be completed before everything else, I think a case could be made for that.

**Comment by brikelly** [comment]
Dang, well, TIL! I had been nuking and re-cloning my repos with a script, but using the same path each time. Now that I've added a datestamp to the repo folder, it works great. Closing this issue now.
