### ISSUE TITLE
OpenAPI should be removed from the Sign In side panel

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-js#1385]
This needs to be removed.
![Image](https://user-images.githubusercontent.com/573108/268425024-8760dab8-38c8-46e6-bd31-e4c1373e755e.png)

**Comment by dustinbyrne** [comment]
OpenAPI generation is still an AppMap capability, it's just not central to the onboarding flow anymore. VS Code users can still access it via command
![image](https://github.com/getappmap/appmap-js/assets/8737782/a0b99c1e-5a4f-45d9-9f33-8b45c5ad0b71)
