### ISSUE TITLE
Upgrade to latest appmap-js components

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-js#1406]

**Comment by evoxf1** [comment]
Hello @brikelly , If your internal team isn't working on this issue or isn't assigned yet internally, may I know what is the status of this issue. And what is the ground work here if you can explain a little bit. I would like to go through the code base and would like to contribute. 
Thanks

**Comment by brikelly** [comment]
Hi @evoxf1 , thanks for your interest! This issue was created in error (in the wrong repo) so I'm going to close it, but if you're looking to help with AppMap then you would need to sign our CLA, which is linked here: https://github.com/getappmap/appmap-ruby/blob/master/CONTRIBUTING.md

Feel free to join our Slack to chat with us directly if you'd like, that link is here: https://appmap.io/community

**Comment by evoxf1** [comment]
@brikelly  thanks for the prompt reply, will do the needful things. I got so interested in this i want to know more.
