### ISSUE TITLE
The auto-collapse number used on map load should be a usable one

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-js#1426]
The auto-collapse depth control always loads with the value `3` initially, but some maps might only have 1 or 2 levels of depth.

![Image](https://github.com/getappmap/appmap-js/assets/573108/675d7bdb-02c1-44e2-9d59-302ce7b20d20)

When using those shallow maps, that means that when the user reduces the depth to 2, they cannot then increase the control back to the value `3`, even though it was originally there. 

## Solution

The max depth is already [dynamically determined](https://github.com/getappmap/appmap-js/blob/main/packages/components/src/components/DiagramSequence.vue#L306), we just need to update the value used in the sequence diagram.

For development, run `yarn storybook` from `packages/components` and visit [this map in storybook](http://localhost:6006/iframe.html?args=scenario:appland1&id=pages-vs-code--extension&viewMode=story) so see the problem.

**Comment by kgilpin** [comment]
I think that having a cap at 9 is potentially problematic. Why don't we use a 2-digit display for the number?

**Comment by brikelly** [comment]
No real reason, other than it seemed like a reasonable upper bound when the feature was first implemented. We can certainly expand it.

**Comment by ahtrotta** [comment]
There was a cap in a prototype, but I removed the cap and it dynamically determines the max depth now.
