### ISSUE TITLE
Filter creates multiple `AppMap default` filters in the browser

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-js#1435]
![Image](https://github.com/getappmap/appmap-js/assets/45714532/9019ef58-da28-4401-b4c1-4642468eeddb)

**Comment by kgilpin** [comment]
Do you have more information about how this occurs and how to reproduce it?

**Comment by ahtrotta** [comment]
Open an AppMap from an AppMap PR report ([here's a recent one](https://getappmap.com/github_artifact?owner=getappmap&repo=appmap-server&run_id=7503869671&base_revision=1d9e16b1783841d0acc60ae8d4a3d163d9283775&head_revision=9361bb62e5ba31f98e375b6b5c3f7701709dd85f&path=head%2Frspec%2FTrialLicenseRequestsController_create_submits_the_new_email_form.appmap.json)) and open the filter menu and you'll see one or more `AppMap default` filters:

![image](https://github.com/getappmap/appmap-js/assets/45714532/7a07af35-0259-4762-b5a5-a5900e797fe4)

If you refresh the page, you'll see one more than last time:

![image](https://github.com/getappmap/appmap-js/assets/45714532/32572039-7da1-4649-a184-0746305ac1fc)
