### ISSUE TITLE
Source links in the project summary are broken

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-js#1453]
Symptom: clicking a source link in a project summary report shows this:

![Image](https://github.com/getappmap/appmap-js/assets/573108/f935247d-5625-42c6-a64e-91549673435d)

[This report](https://github.com/brikelly/sample_rails_app/pull/3#issuecomment-1789732734) demonstrates the issue.

For the links in the project summary, they are formatted like this:
https://github.com/brikelly/sample_rails_app/pull/app/models/user.rb:60

But they need to be formatted like this:
https://github.com/brikelly/sample_rails_app/blob/main/app/models/user.rb#L60 

The `pull/` slug needs to be replaced with `blob/<branch>/ `.

**Comment by kgilpin** [comment]
It looks like the command may just be missing the `--source-url` - https://github.com/getappmap/analyze-action/commit/6ba17052c1de4929b79a1891297add9ff217d85e#diff-36b50cd3b9009f14ee100b397f9313c8277cce6ea54dc7aa696f096e51e53ec9R44

Here's a case where it seems to be done properly - https://github.com/getappmap/analyze-action/commit/ba35d2ecc18dc7b42775c81b54a47e0aae816416#diff-98262750a0b0c2d758b7b60aead675ed400c2b729710e0f68c3ded6258de0050R17

**Comment by kgilpin** [comment]
See also, for reference - https://github.com/getappmap/analyze-action/blob/e77dc2c111ed00aea3be05ca188f49c5508e9161/src/analyze.ts#L94
