### ISSUE TITLE
AI Explain search intermittently unable to find search results. 

### ISSUE THREAD

**Issue by petecheslock** [getappmap/appmap-js#1555]
Using `v0.107.0-rc1` of the VS Code extension, and the [following prompts](https://github.com/land-of-apps/django-oscar/blob/master/demo.md?plain=1#L14-L20) for the [Django Oscar project](https://github.com/land-of-apps/django-oscar/).  A few of the prompts that worked yesterday are now unable to find search results in the appmaps.  

So far i've tried:
a [few different prompts](https://github.com/land-of-apps/django-oscar/blob/master/demo.md?plain=1#L14-L20)
reloading VS Code
stopping VS code and killing any lingering services
full restart of my machine
deleted maps, reset usage state, reloaded, re-recorded specific interaction, asked question.  

Here are the handful of AppMaps from interacting with that project related to new user registration. 
[django-oscar-maps.zip](https://github.com/getappmap/appmap-js/files/13993708/django-oscar-maps.zip)

**Comment by kgilpin** [comment]
Here's an example of how you would test this out locally. 

Clone this project and build it:

```
yarn
yarn build
```

Move to CLI project:

```
cd projects/cli
```

Run the index + RPC server:

```
APPLAND_API_KEY=<your-key> node ./built/cli.js index -d ~/source/land-of-apps/oscar -v -w -p 30101
```

This example assumes you've get a local clone of oscar with the AppMaps attached here; although the indexer will technically work without the source code.

Once you have this running, you can now run the frontend in Storybook:

```
cd packages/components
yarn storybook
```

Open http://localhost:6006/?path=/story/pages-chatsearch--chat-search

30101 is the default port.

To debug the RPC services, run the `index` process in a JavaScript Debug terminal:

<img width="552" alt="Screen Shot 2024-01-19 at 2 49 10 PM" src="https://github.com/getappmap/appmap-js/assets/86395/bd04765a-1dff-4054-9e4e-1dbd695546dd">

You can then set breakpoints anywhere in the index / RPC code base.

**Comment by petecheslock** [comment]
Ok - additional details for next week (ping @apotterri who knows python more and can maybe help be debug)

When i use a [virtual environment](https://github.com/land-of-apps/django-oscar/blob/master/demo.md?plain=1#L3-L9) to build/run the application the appmap indexer process seems to start watching a slew of directories under that venv path ([see the cwd's in this gist](https://gist.github.com/petecheslock/a426ace871e9cb5abfc96fab81694762)).  

when i deactivate my virtual environment, wipe out the venv folder entirely, then reload my vscode only one indexer kicks off

43287 [Stdout] spawned /Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin) --ms-enable-electron-run-as-node /Users/petecheslock/Library/Application Support/Code/User/globalStorage/appland.appmap/node_modules/@appland/appmap/built/cli.js index --watch --port 0 --appmap-dir tmp/appmap with options {"retryTimes":3,"retryThreshold":180000,"id":"index","modulePath":"/Users/petecheslock/Library/Application Support/Code/User/globalStorage/appland.appmap/node_modules/@appland/appmap/built/cli.js","log":{"name":"AppMap: Services"},"args":["index","--watch","--port","0","--appmap-dir","tmp/appmap"],"cwd":"/Users/petecheslock/repos/django-oscar","env":{"APPMAP_API_KEY":"cGV0ZWNoZXNsb2NrQGdtYWlsLmNvbTo1OWU2YTRkYi0wMGI3LTQ3ZjgtOWRkMS03MzE2MWFmNDE1OWQ","APPMAP_API_URL":"https://api.getappmap.com"}}


When i ask the question the answers work again.  So yea i think it has something to do with the VS Code python integration launching many indexers for each directory under "/Users/petecheslock/repos/django-oscar/venv/lib/python3.9/site-packages/_appmap/test/

Then i'm guessing that the Navie Front end hits one of those OTHER indexer RPC ports, but that indexer has only indexed files under venv/lib/python3.9/site-packages/_appmap/test/  and therefore finds no details.

**Comment by petecheslock** [comment]
@kgilpin should we close this issue since the appmap-python issue is now resolved - or leave it open because there could be a scenario where a single project has multiple appmaps and might see the same problem with the AI:Explain?

**Comment by kgilpin** [comment]
IMO we can close it because there is a separate issue to ask the user which directory they want to use if there are multiple indexers running.
