### ISSUE TITLE
Add an introduction to Navie in code editor instructions flow

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-js#1570]

**Comment by kgilpin** [comment]
I'd like to suggest that we incorporate Navie directly into Step 3 rather than making it Step 4:

<img width="1185" alt="Screen Shot 2024-01-26 at 4 42 14 PM" src="https://github.com/getappmap/appmap-js/assets/86395/63500754-1764-40d9-8bf1-ff59d6dcfae6">

**Comment by ahtrotta** [comment]
We decided not to include a separate instructions page. Instead, we made it so that the Navie chat interface is opened as part of the instructions flow.
