### ISSUE TITLE
Server-side messages reported via tokens are not visible to the client through RPC

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-js#1601]
The socket is closed, and no message is reported to the client.

They see "failed to fetch".

**Comment by kgilpin** [comment]
Can we move some of these interactions to regular web services? I think that if we had been able to see the HTTP logs on the server it would have been a lot more clear what was going on. 

I do not like the invisibility of the socket transport. I would prefer the use of socket over web services ONLY when necessary.
