### ISSUE TITLE
"New Chat" button opens a new tab instead of clearing the chat

### ISSUE THREAD

**Issue by dividedmind** [getappmap/appmap-js#1922]
- [x] Support editor-provided function for new chat (https://github.com/getappmap/appmap-js/pull/1925)
- [x] Provide a function to open new chat in VSCode (https://github.com/getappmap/vscode-appland/pull/995)
- [x] Provide a function to open new chat in JetBrains (https://github.com/getappmap/appmap-intellij-plugin/pull/760)

**Comment by kgilpin** [comment]
It could open a whole new Navie window. Maybe that’s what you mean?

**Comment by dividedmind** [comment]
> It could open a whole new Navie window. Maybe that’s what you mean?

Yes, that's what it's doing, see the PRs.

**Comment by kgilpin** [comment]
I don’t read code I only read Navie descriptions :-)

**Comment by kgilpin** [comment]
There could be a diagram here, a check list - it would all be so clear!
