### ISSUE TITLE
Accept '/' as the command delimiter in addition to '@'

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-js#1941]
Currently, our commands such as @help, @plan are triggered by the `@` character.

It seems more standard to use `/` instead.

Refactor the code in the `navie` project to accept `/` as the command delimiter, in addition to the current `@`.

**Comment by dividedmind** [comment]
I don't think it's a good idea:
- It feels bikesheddy and not doing anything to solve the primary problem of discoverability.
- The modes are more like agents than commands (at least some of them) and @ seems to be the convention for agents.
- If we do go forward with this, I'd make the code recognize the old style too.
- It seems simple on the surface, but there might be more code and documentation that relies on the current syntax than we realize, which will be a timesink to discover and fix.

**Comment by kgilpin** [comment]
No plan to implement
