### ISSUE TITLE
Validate `@suggest` prompts do not clobber `@explain` chat history

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-js#1982]
When a user asks a follow-up question, recent messages in the thread are included in the LLM context.

Each time the user asks a question, the UI a send `@suggest` request on behalf of the user. This @suggest message, being part of the conversation, is then considered part of the conversation history when the user asks a question.

We don't want this behavior; because it's not actually something that the user is aware of.

Ensure that `@suggest` prompts and responses are **not** included in the chat history ingested by `@explain`, otherwise the output may be affected.

Consider issuing the @suggest request outside of the user's conversation thread. That way it won't be included in the message history.

—

Implement this within the Ui components, RPC and CLI packages as necessary; not within the Navie package.

**Comment by kgilpin** [comment]
@dustinbyrne how does this look? ⬆️

**Comment by dustinbyrne** [comment]
This change is going to have to affect `@appland/navie` in one way or another. `@suggest` uses the chat history to generate the next step completions. By dropping or changing the thread id, we'd lose that information.

**Comment by dustinbyrne** [comment]
After giving it some thought, a proper fix is sort of non-trivial as I believe this warrants some additional abstraction which may affect the backend. 

As I see it, in order to solve this, we'd need one of the following:
- a method of assigning messages some sort of metadata and persisting it (such as flagging a message as functional, or non-conversational)
- a separate means of retrieving conversation history outside of the current thread
- a rework of `@suggest` to include the relevant conversation history in the prompt text, assigning a new thread id

I've put together a naive fix as an interim measure: https://github.com/getappmap/appmap-js/pull/1989

**Comment by kgilpin** [comment]
@dustinbyrne looks like this is resolved?
