### ISSUE TITLE
Navie Copilot Backend link is 404

### ISSUE THREAD

**Issue by kgilpin** [getappmap/appmap-js#2065]
https://appmap.io/docs/navie-reference/navie-copilot-backend.html

Follow Learn More link:

<img width="444" alt="Screen Shot 2024-10-15 at 9 53 52 AM" src="https://github.com/user-attachments/assets/e4425872-bcc4-4ba0-a875-ce20fb730b5d">

**Comment by petecheslock** [comment]
A quick fix for this can be this redirect i setup in this PR, alternatively we can point the landing page elsewhere.
