### ISSUE TITLE
Update Runtime Analysis CTA wording in sidebar

### ISSUE THREAD

**Issue by Daniel-Warner-X** [getappmap/appmap-js#662]
Change this string:
"Issues found by runtime analysis of your code"
Screenshot: https://files.slack.com/files-pri/TF93Z92M8-F03MUTF6L77/screen_shot_2022-06-30_at_6.45.55_pm.png

To this string:
"AppMap can help you find and fix problems in your code before you commit and ship."

**Comment by ahtrotta** [comment]
Closing because this has been changed
