### ISSUE TITLE
`bundle` run from the installer may compile for the wrong architecture on M1/M2 chips

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-js#705]
via @dividedmind

Running node sets up Rosetta environment which causes gem to use x64 compiler to build the gem even though ruby is native (because node executes gem in its, rosetta'd, environment). This will lead to an arch mismatch when native ruby tries to load an x64 dylib.

The solution would be to make sure bundle is ran in an environment without any Rosetta leftovers. The current workaround is to remove the (miscompiled) gem and reinstall it by running bundle manually.

**Comment by ahtrotta** [comment]
Closing because this was addressed by: https://github.com/getappmap/appmap-ruby/issues/286

**Comment by dividedmind** [comment]
> Closing because this was addressed by: [getappmap/appmap-ruby#286](https://github.com/getappmap/appmap-ruby/issues/286)

Ok, thanks; I created a new issue to track the idea of automatically installing it correctly.

**Comment by ahtrotta** [comment]
Okay, that's a good idea!
