### ISSUE TITLE
File watcher does not notice re-appearing directories and files

### ISSUE THREAD

**Issue by jansorg** [getappmap/appmap-js#724]
When I have a directory `target/appmap` and then launch both the CLIs via `appmap index --watch --appmap-dir /path/to/dir` and `scanner --watch --appmap-dir /path/to/dir`, then the AppMap files in `target/appmap` are properly located and processed.

But when I keep the processes running, then remove `target` and re-create it (e.g. with the npx command to run tests), then the new AppMap files at `target/appmap` are NOT located and processed.

This should help to reproduce:
1. create AppMap files, e.g. at `target/appmap`
2. Launch both CLIs in watch mode
3. Wait until files are processed
4. `rm -rf target`
5. re-create the files at `target/appmap`
6. The index files and finding files are NOT created for the newly created AppMaps

Tested with
- Linux
- Scanner CLI 1.70.1
- AppMap CLI 3.35.0

**Comment by brikelly** [comment]
@dividedmind do you have any update on the progress of this item?

**Comment by dividedmind** [comment]
> @dividedmind do you have any update on the progress of this item?

It's tricky. I can reproduce the problem manually but it disappears in tests. Still trying to figure out why. :/

**Comment by kgilpin** [comment]
Why don't we just re-scan periodically?

When I read various literal and man pages on file watching, they all
suggested this. They said that file watching would always be a bit flaky,
and it's a GOOD IDEA to periodically re-scan the directory.

With the --watch flag enabled, all we would need to do is set a time every
few seconds and scan the directory - then the file watching provides
realtime updates for a best-case better behavior.

**Comment by kgilpin** [comment]
It seems like we are bashing our heads against chokidar instead of just
re-scanning.

**Comment by dividedmind** [comment]
This should have been fixed (in a way) by #743 . Please reopen if you still see this issue.
