### ISSUE TITLE
`scan --watch` is not working on Windows

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-js#726]
Even when running `scan --watch` with existing indexes and running `touch` on the `mtime` files, no scans occur. `scan --all` works as intended.

**Comment by jansorg** [comment]
@brikelly I think this is significant for the IntelliJ support. What do you think?

**Comment by brikelly** [comment]
Yes it is crucial for IntelliJ (and likely VS Code too) to work.

**Comment by kgilpin** [comment]
Dustin and I feel like this is a big risk for TC. Would like to see this
resolved as soon as possible.

**Comment by ahtrotta** [comment]
Yup, I'll try to wrap up what I'm working on ASAP so I can get to this.

**Comment by dustinbyrne** [comment]
This is resolved by [#743](https://github.com/getappmap/appmap-js/pull/743)
