### ISSUE TITLE
While recording tests, the recommended command includes a package specifier for JavaScript

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-js#795]
https://github.com/getappmap/appmap-js/blob/6b73f527b81e1f8c7f26adde5a5411efa3798428/packages/cli/src/cmds/record/action/guessTestCommands.ts#L44

Some users can't resolve `appland-agent-js` via `npx` despite the installer (seemingly) succeeding. The command should recommend the fully qualified package instead (`@appland/appmap-agent-js`).

**Comment by brikelly** [comment]
I believe https://github.com/getappmap/appmap-js/pull/800 fixes this

**Comment by dustinbyrne** [comment]
Yes, closing this.
