### ISSUE TITLE
Installer fails to correctly detect version manager in a python project

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-js#810]
[Here's the Azure log](https://portal.azure.com/#view/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222022-10-21T21%3A51%3A12.226Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222022-10-21T21%3A51%3A12.226Z%22))%20and%20customDimensions%5B%22appmap.cli.sessionId%22%5D%20contains%20%222403335f938d8ff9d0e9fb5f8222d5b345b0e11e7aeb94f4477e343a776b51ca%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%7C%20project-reorder%20%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog)
```
Error: An error occurred while running the command: poetry add --dev --allow-prereleases appmap
The command exited with code 1
```
```
> Command '['/home/carlos/.cache/pypoetry/virtualenvs/client-25Pz9rbF-py3.10/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/home/carlos/.cache/pypoetry/virtualenvs/client-25Pz9rbF-py3.10', '--no-deps', '/home/carlos/.cache/pypoetry/artifacts/6d/04/93/039969613ee6ada8686d86d46554e642707c2ca621adc64785df0bac5e/redislite-6.0.674960.tar.gz']' returned non-zero exit status 1.
```

[Here's another example](https://portal.azure.com/#view/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222022-10-21T22%3A13%3A00.72Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222022-10-21T22%3A13%3A00.72Z%22))%20and%20customDimensions%5B%22appmap.cli.sessionId%22%5D%20contains%20%222403335f938d8ff9d0e9fb5f8222d5b345b0e11e7aeb94f4477e343a776b51ca%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%7C%20project-reorder%20%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog)

**Comment by apotterri** [comment]
The installer did the right thing here: there's a `poetry.lock` file in the project, so it ran `poetry` to do the install. The user's environment is broken, though, so when `poetry` invoked `pip` to install a dependency, `pip` failed. (Note that both telemetry events are from the same user, for the same project.)
