### ISSUE TITLE
EACCES error when installing

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-js#812]
From this [log](https://portal.azure.com/#view/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222022-10-23T07%3A41%3A56.997Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222022-10-23T07%3A41%3A56.997Z%22))%20and%20customDimensions%5B%22appmap.cli.sessionId%22%5D%20contains%20%22ca8961eb1603284c13c42604a5c50b7b00d1d7968c0224eee116dee97d75a027%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%7C%20project-reorder%20%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog). Might be an issue with Windows Subsystem for LInux?:
```
npm ERR! code EACCES
npm ERR! syscall rename
npm ERR! path node_modules/qq
npm ERR! dest node_modules/.qq-vOW0uscM
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, rename 'node_modules/qq' -> 'node_modules/.qq-vOW0uscM'
npm ERR!  [Error: EACCES: permission denied, rename 'node_modules/qq' -> 'node_modules/.qq-vOW0uscM'] {
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'node_modules/qq',
npm ERR!   dest: 'node_modules/.qq-vOW0uscM'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
```

**Comment by dustinbyrne** [comment]
This looks like a user error. I'm guessing `npm` is trying to update this package but can't due to permissions.

**Comment by ahtrotta** [comment]
Yup, this looks like user error to me on second look.
