### ISSUE TITLE
`appmap:print-jar-path`

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-js#814]
From this [log](https://portal.azure.com/#view/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222022-10-24T07%3A36%3A14.846Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222022-10-24T07%3A36%3A14.846Z%22))%20and%20customDimensions%5B%22appmap.cli.sessionId%22%5D%20contains%20%225a68a174a8fba29b100f158df52e4e7765834c3f13d4e4ee2713e0132dafcc7d%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%7C%20project-reorder%20%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog):
```
Error: An error occurred while running the command: mvn.cmd appmap:print-jar-path
The command exited with code 1
```

[Here's another log](https://portal.azure.com/#view/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222022-10-24T07%3A46%3A15.014Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222022-10-24T07%3A46%3A15.014Z%22))%20and%20customDimensions%5B%22appmap.cli.sessionId%22%5D%20contains%20%225a68a174a8fba29b100f158df52e4e7765834c3f13d4e4ee2713e0132dafcc7d%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%7C%20project-reorder%20%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog)

**Comment by apotterri** [comment]
This was a problem in the user's project. Maven started to install dependencies when it was asked to run the `print-jar-path`, but something failed to install properly.
