### ISSUE TITLE
Try (and suggest) running python with python3

### ISSUE THREAD

**Issue by dividedmind** [getappmap/appmap-js#839]
Some systems have default python set to python 2, but python 3 is still available as `python3`. We should consider suggesting and trying to run python and pip as `python3` and `pip3` to help users of these systems.

**Comment by symwell** [comment]
We officially support only Python >=3.7, <= 3.10.

Rather than suggest anything to the user, it seems it would work to always call `python3` and `pip3` instead of `python` and `pip`.

**Comment by dividedmind** [comment]
> We officially support only Python >=3.7, <= 3.10.
> 
> Rather than suggest anything to the user, it seems it would work to always call `python3` and `pip3` instead of `python` and `pip`. Right? If it doesn't work because they only have python v2, then possibly suggest running python (which would be v2).
> 
> It's strange our default is to call a python version we don't support.

This is what I meant :) Our default is `python` because on most systems it's python 3.

One concern I have is that I'm not 100% sure `python3` will always be a valid command (even if `python` is python 3). Can that be guaranteed?

**Comment by symwell** [comment]
I don't know if it can be guaranteed. On Ubuntu the file `python3` is probably created by a post-installation script.  I don't see it in the [package](https://packages.debian.org/bullseye/amd64/python3/filelist)  (http://packages.ubuntu.com/ isn't loading for me right now.)

I don't know if the default `python` on most systems is python 3.  On Ubuntu installing python 3  requires `apt install python3`.  If you do `apt install python` it installs python 2.

I don't know about MacOS or Windows.

**Comment by dividedmind** [comment]
Yeah, python3 command on ubuntu is probably set up by some `alternatives` mechanism.

[PEP 394](https://peps.python.org/pep-0394/) suggests `python3` should always be present, but it doesn't make the same guarantees for `pip3`.

**Comment by symwell** [comment]
[PEP 439](https://peps.python.org/pep-0439/) says "The Python installation includes an executable called “pip3” (see [PEP 394](https://peps.python.org/pep-0394) for naming rationale etc.) that attempts to import pip machinery."

**Comment by dividedmind** [comment]
> [PEP 439](https://peps.python.org/pep-0439/) says "The Python installation includes an executable called “pip3” (see [PEP 394](https://peps.python.org/pep-0394) for naming rationale etc.) that attempts to import pip machinery."

Nice find, thanks!
