### ISSUE TITLE
Scanner crashes

### ISSUE THREAD

**Issue by symwell** [getappmap/appmap-js#851]
https://applanding.slack.com/archives/C02DU9210Q2/p1668195251496149

dustinbyrne  reports:

The scanner crashes if you don't have a tmp/appmap directory - we still need to fix this

if it crashes three times it gives up

**Comment by kgilpin** [comment]
I don’t think so. This is due to the way that the extensions batches up
work.

**Comment by dustinbyrne** [comment]
This is fixed in https://github.com/getappmap/vscode-appland/pull/532
