### ISSUE TITLE
`EACCES: permission denied` causes indexer to exit with exit code 1

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-js#899]
[Here's](https://portal.azure.com/#view/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222022-12-09T05%3A16%3A22.648Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222022-12-09T05%3A16%3A22.648Z%22))%20and%20session_Id%20%3D%3D%20%22e655af7b-8018-4062-950a-24bf8336bff91670562802093%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%2Cexception%3DcustomDimensions%5B%22appmap.debug.exception%22%5D%7C%20project-reorder%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog%2Cexception) an example:
```
Error: EACCES: permission denied, scandir '/path/'
Emitted 'error' event on Glob instance at:
    at Glob._readdirError (/path/Code/User/globalStorage/appland.appmap/node_modules/glob/glob.js:610:14)
    at /path/.config/Code/User/globalStorage/appland.appmap/node_modules/glob/glob.js:553:12
    at FSReqCallback.oncomplete (node:fs:188:23) {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '/path/'
}
```

**Comment by symwell** [comment]
The log above is for the indexer, not the scanner. Was able to reproduce this error for the scanner.

I expected to find a `scandir` system call as the one shown in the log but observed a `watch` system call.  It could be because the log message above was for the indexer, not the scanner.  Disabling the watcher to leave only the poller running didn't produce an `EACCES` error.  Hardcoding an inaccessible `this.options.configFile` produced an `EACCES` error for a `stat` system call
```
$ yarn run scanner scan --watch --appmap-dir ~/tmp/permission_denied
Using scanner configuration file /home/test/src/appmap-js/packages/scanner/built/sampleConfig/default.yml
configfile is /home/test/tmp/permission_denied/minitest/User_should_be_valid/appmap-scanner.yml
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: EACCES: permission denied, stat '/home/test/tmp/permission_denied/minitest/User_should_be_valid/appmap-scanner.yml'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (/home/test/src/appmap-js/node_modules/chokidar/index.js:647:10)
    at NodeFsHandler._addToNodeFs (/home/test/src/appmap-js/node_modules/chokidar/lib/nodefs-handler.js:645:18)
    at async /home/test/src/appmap-js/node_modules/chokidar/index.js:451:21
    at async Promise.all (index 0) {
  errno: -13,
  code: 'EACCES',
  syscall: 'stat',
  path: '/home/test/tmp/permission_denied/minitest/User_should_be_valid/appmap-scanner.yml'
}

Node.js v18.8.0
```

**Comment by ahtrotta** [comment]
Okay, I re-named the issue, thanks!
