### ISSUE TITLE
`FATAL ERROR: ... JavaScript heap out of memory` when running Indexer

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-js#900]
[Here's](https://portal.azure.com/#view/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222022-12-09T16%3A31%3A04.205Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222022-12-09T16%3A31%3A04.205Z%22))%20and%20session_Id%20%3D%3D%20%220e76fee4-8062-41ad-9018-d252739a47ff1670599587212%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%2Cexception%3DcustomDimensions%5B%22appmap.debug.exception%22%5D%7C%20project-reorder%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog%2Cexception) an example

**Comment by symwell** [comment]
A similar out of memory error is described in https://github.com/getappmap/appmap-js/issues/886.

**Comment by ahtrotta** [comment]
Yup, it's a duplicate
