### ISSUE TITLE
`Error: Cannot find module '@datastructures-js/priority-queue'`

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-js#914]
[Example](https://portal.azure.com/#view/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222022-12-16T05%3A00%3A03.18Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222022-12-16T05%3A00%3A03.18Z%22))%20and%20session_Id%20%3D%3D%20%2215d45592-dc25-44a7-9464-2a18004e52bd1671123973642%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%2Cexception%3DcustomDimensions%5B%22appmap.debug.exception%22%5D%7C%20project-reorder%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog%2Cexception)

**Comment by kgilpin** [comment]
Can you look at this and see if there’s something wrong:

https://github.com/getappmap/appmap-js/pull/913/commits/0a98c56ec86250be64555a2a2fb22e63dad63ffd

I wanted to link appmap-js in our VSCode plug-in and it would work without these changes.

**Comment by ahtrotta** [comment]
I'm not seeing the problem after a quick look, but I can dig into it later

**Comment by ahtrotta** [comment]
It's also happening when users run [openapi](https://portal.azure.com/#view/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Fa4af4729-21ee-4e0a-953c-33cc9db5295c%2Fresourcegroups%2Fvscode-extension%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fvscode-extension-analytics/source/AIExtension.SearchV2/query/union%20customEvents%20%7C%20where%20timestamp%20%3E%3D%20datetime(%222022-12-16T06%3A18%3A43.831Z%22)%20and%20timestamp%20%3C%3D%20(datetime(%222022-12-16T06%3A18%3A43.831Z%22))%20and%20session_Id%20%3D%3D%20%2215d45592-dc25-44a7-9464-2a18004e52bd1671123973642%22%7C%20extend%20logLen%3Dstrlen(customDimensions%5B%22appmap.cli.log%22%5D)%2Clog%3DcustomDimensions%5B%22appmap.cli.log%22%5D%2Cexception%3DcustomDimensions%5B%22appmap.debug.exception%22%5D%7C%20project-reorder%20timestamp%2Cname%2Cuser_Id%2ClogLen%2Clog%2Cexception)

**Comment by ahtrotta** [comment]
Can we just revert [this line](https://github.com/getappmap/appmap-js/commit/0a98c56ec86250be64555a2a2fb22e63dad63ffd#diff-6e2e2a1851648938b325ba84de634407a4e69a644ea61102df15ca4a8a7a9758L74)?

**Comment by kgilpin** [comment]
But where is priority-queue being used in the CLI project? I only see it
being used in sequence-diagram which is why I moved the import over there.

**Comment by brikelly** [comment]
This has been merged and released (with a direct commit to main).

**Comment by symwell** [comment]
If the direct commit to main was https://github.com/getappmap/appmap-js/commit/25055fb227c4088abecaa2de87d5c13f6d5dd9b3 on Dec 16 2022 right after the 1.74.2 release, then it must be included in 1.74.3 on Dec 21 2022.
