### ISSUE TITLE
The CLI can upload maps to the server

### ISSUE THREAD

**Issue by brikelly** [getappmap/appmap-js#962]
The old appland CLI tool (written in Golang) supports the `upload` command. We need to port that command (https://github.com/getappmap/appland-cli#upload) to the JS/TS CLI. We do not need to port the authentication or contexts features. Just expect APPLAND_API_KEY or APPMAP_API_KEY in the environment. stats has already been ported over.

**Comment by dividedmind** [comment]
> @dividedmind any update on this yet?

Sorry, had a rough week. PR now pushed.
