### ISSUE TITLE
Scan and index: High CPU usage when idle

### ISSUE THREAD

**Issue by dustinbyrne** [getappmap/appmap-js#969]
![Image](https://user-images.githubusercontent.com/8737782/214121561-a52bdc75-7281-4cde-951e-1f749df0d696.png)

**Comment by dustinbyrne** [comment]
I've narrowed it down to this class: https://github.com/getappmap/appmap-js/blob/main/packages/cli/src/fingerprint/globber.ts

**Comment by apotterri** [comment]
Things I've learned so far:
* turning off the globber eliminates idle CPU usage
* it takes a bit over 300ms (4x that when run in the debugger) for globber to scan the 620 `*.appmap.json` files in my `appland-server` `tmp/appmap` directory. Delta is measured from right before the call to `new Glob()`, up until the time `'end'` is received, so it includes the time Glob takes, as well as the 620 calls to `stat`.
* scans are run sequentially: the next scan is [scheduled](https://github.com/getappmap/appmap-js/blob/4b0dff93455c52be1b5d377cf3bed946ab7ec640/packages/cli/src/fingerprint/globber.ts#L53) to run 1s after processing is finished for an `'end'` event.

**Comment by kgilpin** [comment]
Wow. That’s an insane amount of time to examine 600 files.

**Comment by apotterri** [comment]
>  as well as the 620 calls to stat.
This actually isn't right: each call to `stat` is async, and there's nothing that ensures that it's finished before the `'end'` event is emitted by `Glob`.

So, the 300ms is actually *just* the time `Glob` takes to scan the tree.

**Comment by kgilpin** [comment]
I’m not sure how I would write it to be that slow if I tried.
